### PR TITLE
Validate input for adding a team member and added tests

### LINKED ISSUE #88: AddTeamMemberForm Doesn't Validate Fields
POST requests for new Team Members must contain values for "name" and "title" fields, however, the `AddTeamMemberForm.jsx` component does not require that the user enter values for these fields before submitting the form. It will simply send a request with one or both fields empty. The result is a failed POST, but no notification to alert the user of this fact.

**After the user clicks the "Submit" button, the component should `alert` the user if both fields are not populated and refuse to submit the request unless they are.**

### PR DESCRIPTION
**Pull request by solkaz**
Fixes #88

### CODE REVIEW

File: src/AddTeamMemberForm.jsx [hunk 1]
```diff
@@ -14,21 +14,30 @@ class AddTeamMemberForm extends React.Component {
   }
   onChange(key) {
     // Return a curried function that sets a value to the key in this.state
-    return function(value) {
+    return (value) => {
```
Comment (Hopding) [inline src/AddTeamMemberForm.jsx:20]: I'm not requesting that you change this, but I just wanted to note that I believe if you have an anonymous function with only one parameter, you do not need parenthesis, e.g. you could have written:
```javascript
return value => {
  /* ... */
}
```
instead of
```javascript
return (value) => {
  /* ... */
}
```

File: src/AddTeamMemberForm.test.jsx [hunk 2]
```diff
@@ -0,0 +1,33 @@
+import React from 'react';
```
Comment (Hopding) [inline src/AddTeamMemberForm.test.jsx:1]: Nice refactoring of these tests - much better!

**Review by Hopding — APPROVED** [review]
Noice 👍

**Review by thebho — APPROVED** [review]

**Comment by thebho** [comment]
More conflicts

File: src/AddTeamMemberForm.jsx (hunk 1 above)
Comment (solkaz) [reply src/AddTeamMemberForm.jsx:20]: Per [this](http://eslint.org/docs/rules/arrow-parens) eslint rule, a parenthesis is "required," although it is acceptable syntax to omit it in this case.
